spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchangeRate?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  error:
    include-message: always