spring:
  datasource:
    url: jdbc:mysql://exchangeratedbinstance.cxc48oemw73x.ap-south-1.rds.amazonaws.com:3306/db?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: Admin1234

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  error:
    include-message: always