name: cicd
on:
  push:
    branches: [feature-Vidura-merge]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Login Dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build the Image
        run: docker build -t viduradocker1/exchangerateappdocker .
      - name: Push to Image to Docker Repository
        run: docker push viduradocker1/exchangerateappdocker:latest

  deploy:
    needs: [build]
    runs-on: [ec2-exchrate]
    steps:
      - name: Pull the Docker Image
        run: docker pull viduradocker1/exchangerateappdocker
      - name: Delete the instance
        run: docker rm -f exchrate-container
      - name: Run the Image in Container
        run: docker run -d -p 8085:8085 --name exchrate-container viduradocker1/exchangerateappdocker
